=== Abdelhafid2/xml-bourse/bource.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xsd:element name="bource">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="societe" type="typeSociete" minOccurs="1" maxOccurs="unbounded"></xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:complexType name="typeSociete">
        <xsd:sequence>
            <xsd:element name="codeSociete" type="xsd:string"/>
            <xsd:element name="nomSociete" type="xsd:string"/>
            <xsd:element name="dateIntroduction" type="xsd:date"/>
            <xsd:element name="cotations" type="typeCotation"/>
        </xsd:sequence>
        <xsd:attribute name="type" type="typeType" use="required"></xsd:attribute>
    </xsd:complexType>
    
    <xsd:complexType name="typeCotation">
        <xsd:sequence>
            <xsd:element name="cotation" type="cotationType" minOccurs="1" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="cotationType">
        <xsd:attribute name="num" type="xsd:positiveInteger" use="required"/>
        <xsd:attribute name="dateCotation" type="xsd:date" use="required"/>
        <xsd:attribute name="valeurAction" type="xsd:positiveInteger" use="required"/>
    </xsd:complexType>
    
    <xsd:simpleType name="typeType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Assurance"/>
            <xsd:enumeration value="Bank"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== Abdelhafid2/xml-bourse/bource.xml
<?xml version="1.0" encoding="UTF-8"?>
<bource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/Users/coder/OneDrive/Bureau/wisd/echangeDeDonnees/bource.xsd">
    <societe type="Assurance">
        <codeSociete>1222</codeSociete>
        <nomSociete>nom1</nomSociete>
        <dateIntroduction>2002-12-12</dateIntroduction>
        <cotations>
            <cotation num="11" dateCotation="2000-06-09" valeurAction="12"/>
            <cotation num="11" dateCotation="2000-06-09" valeurAction="12"/>
            <cotation num="11" dateCotation="2000-06-09" valeurAction="12"/>
            <cotation num="11" dateCotation="2000-06-09" valeurAction="12"/>
        </cotations>
    </societe>
    
    <societe type="Bank">
        <codeSociete>22</codeSociete>
        <nomSociete>bank1</nomSociete>
        <dateIntroduction>2002-12-12</dateIntroduction>
        <cotations>
            <cotation num="11" dateCotation="2000-06-09" valeurAction="12"/>
            <cotation num="11" dateCotation="2000-06-09" valeurAction="12"/>
            <cotation num="11" dateCotation="2000-06-09" valeurAction="12"/>
            <cotation num="11" dateCotation="2000-06-09" valeurAction="1"/>
        </cotations>
    </societe>
</bource>
